    @include('partials.header')
    @include('partials.nav')
    <main>
        @yield('index')
        @yield('articles')
        @yield('article')
        @yield('backofficeIndex')
        @yield('addArticle')
        @yield('editArticle')
    </main>
    @include('partials.footer')
